### ISSUE TITLE
Iframe is inserted in vue will be reloaded

### ISSUE THREAD

**Issue by yoyomule** [wefront/feb-alive#1]
Iframe is inserted in vue, but the iframe page will be reloaded when switching between different pages. Can this be added to the firame framework?

**Comment by hangaoke1** [comment]
<iframe>s will reload whenever they are detached from the document (or after inserting them to a new location).  you can see similar issue in Vue issues, eg https://github.com/vuejs/vue/issues/9473

**Comment by yoyomule** [comment]
Vue-router mode iframe will be reloaded, this seems to be a problem with vue itself? There seems to be no solution to this problem, except for v-show?

**Comment by hangaoke1** [comment]
Maybe Vue can optimize it, but it is the reason of  browser. When you remove the iframe from the DOM, even if there is an iframe DOM object in JavaScript, when you append it to DOM again will trigger the reload of the iframe. v-show is ok, 
but not for all scenarios
