### ISSUE TITLE
有一个问题想要请教

### ISSUE THREAD

**Issue by Dante-dan** [wefront/feb-alive#11]
https://github.com/wefront/feb-alive/blob/2fd3cd1ce501dfcc71fdd0127a05c0c52e90352c/src/index.js#L148

>       Vue.location.recoverMeta(from, to)

看到 recoverMeta 会修改路由的 meta 信息，但是我理解 meta 和 route 应该是绑定的，并且不应该被修改。为什么在命中某些判断之后去修改 meta 呢？
当多次 replace 同一个路径，是不是会存在潜在的 meta 信息错乱的问题。

**Comment by hangaoke1** [comment]
meta 是和 页面历史栈绑定的，比如页面路径是 pageA [mataA] ---> pageB[mataB] ---> pageA[mataA New]，第三个pageA如果是前进的，则会返回一个新的mataA New。如果是replace同一个路径 或者 后退到PageA，则会复用页面的meta缓存。当然replace到同一个路径这种业务场景比较特殊，大部分只是替换一下路由的url查询参数，所以复用了meta缓存，这部分可以考虑增加配置，让使用者决定是否复用meta

**Comment by hangaoke1** [comment]
当然在路由初始化的时候，会把初始化的meta存储起来，所以不会影响真正绑定到路由上面的meta信息
https://github.com/wefront/feb-alive/blob/6cab419a00ab4ce04abb6a982da6d91c06761133/src/utils.js#L130
