### ISSUE TITLE
feb-alive 的子路由保活

### ISSUE THREAD

**Issue by Dante-dan** [wefront/feb-alive#15]
当父路由是动态路由时，父子路由的保活好像有些问题。

[父路由是动态路由时的保活](https://codesandbox.io/s/purple-platform-q1i1k?file=/src/App.vue)

如上示例中所看到的：

1. 当进入 `/b/{random}` 之后，再切换子路由，只会触发子路由的改变，而父路由不会再重新 `mounted`。
2. 当进入 `/b/{random}/sub` 的子路由之后，再进入父路由 `/b/{random}` ,  再使用浏览器的返回，返回到 `/b/{random}/sub` 此时父路由重新 `mounted` 。

对于场景 2，预期应该是能复用上次路由的结果。

-----
大概 `Debug` 了一下，[父路由通过 Key 复用](https://github.com/wefront/feb-alive/blob/3a92eda9e109fd9fe85a7e994b2fcffa6ee01c73/src/components/feb-alive.js#L110) 大概和这一行有关系。

我理解因为是动态路由，所以通过 `key` 复用，是会在 `patch` 阶段被重新挂载的。

**Comment by hangaoke1** [comment]
好像是有点问题，目前设计是，嵌套路由跳转中，共享的父路由是根据key直接复用的，走的vue原生的diff逻辑。你的问题我之后看下怎么修复。是这个判断导致的https://github.com/wefront/feb-alive/blob/master/src/components/feb-alive.js#L98，因为你这种情况 两个跳转的路由匹配到的组件 深度不一样了

**Comment by Dante-dan** [comment]
emmmmm, 这应该是两个问题。

按照我理解，应该是判断 `fullpath` 来判断是否能复用。我  `debug` 看到，父组件有一次 `match` ，子组件一次 `match` 应该是没有匹配深度的问题。

至于使用 key 复用，还是实例复用。

其实不太理解，为什么父组件不通过实例复用，会有什么问题吗？

**Comment by hangaoke1** [comment]
fixed in v2.0.1
[示例演示](https://hangaoke1.github.io/feb-alive/tree-ancestor/tree-parent/tree-son)

**Comment by Dante-dan** [comment]
链接挂掉了。😢

**Comment by hangaoke1** [comment]
再试下，部署的gh-page有点问题
