### ISSUE TITLE
路由变化时，feb-alive 会重新 render

### ISSUE THREAD

**Issue by Dante-dan** [wefront/feb-alive#16]
https://github.com/wefront/feb-alive/blob/e6b10f75119593b98a122a49514d382d584eed38/src/components/feb-alive.js#L38

这个是咋实现的吖，我没有看到 `foreceUpdate` 的代码，而且这样可能会有问题。

这种每次路由变化都 render 的实现方式，会导致嵌套路由时，不该 render 的 feb-alive 重新缓存了新的 vnode

**Comment by hangaoke1** [comment]
这个是vue源码中逻辑，可阅读[vue技术内幕](https://ustbhuangyi.github.io/vue-analysis/v2/extend/keep-alive.html#%E7%BB%84%E4%BB%B6%E6%B8%B2%E6%9F%93)

![image](https://user-images.githubusercontent.com/19623160/125725581-a8aa52fa-f2a0-41d3-8786-ddd69289ac40.png)

**Comment by Dante-dan** [comment]
梳理了一下，`<feb-alive>` 或者 `<keep-alive>` 都会在 `prepatch` 阶段对 `children` 执行 `forceUpdate` 。

因为 `keep-alive` 使用 `vnode.key` 或者 ` componentOptions.Ctor.cid + componentOptions.tag` 作为唯一的 `key` ，所以其需要渲染的 `vnode` 的 `key` 是稳定的，每次 `render` 都会得到同样 `key` 的 `vnode` 。

1. `feb-alive` 使用的 `key` 是 `history.state.key` 是不稳定的。
2. `feb-alive` 的 `render` 会一直执行，无法命中 `cache` 中的 `key`。
3. 最终会在已经 `inactive` 的 `feb-alive` 中， 不断 render `key` 不同，其余相同的 `vnode`。

嵌套路由中，这种情况会更严重。

**Comment by hangaoke1** [comment]
缓存命中是根据`history.state.key`来的，比如你路由前进，那么都会被当作新开的页面，生成新的页面实例，只有后退的时候才会命中缓存。控制台输入`window. debug_cache` 可以看到所有缓存的情况，可以来个示例说明下问题，我可能没有理解你的实际场景

**Comment by hangaoke1** [comment]
另外`history.state.key` 对于同一个页面来说，永远是稳定的。

**Comment by hangaoke1** [comment]
针对非active的feb-alive组件，继续缓存页面这个问题，我修复一下

**Comment by hangaoke1** [comment]
fix v2.02

**Comment by Dante-dan** [comment]
```html
<feb-alive>
  <router-view>
    <feb-alive v-if="$route.path === 'home'"  key="foo">
      <router-view></router-view>
    </feb-alive>
    <feb-alive v-else key="bar">
      <router-view></router-view>
    </feb-alive>
  </router-view>
</feb-alive>
```

以上代码只是举个例子。对于 `keep-alive` 而言，`foo` 的 `children` 本来只会是固定的二级路由，`key = component.tag` , 认为是**稳定的**。所以即使 `foo` 已经失活，也不会产生额外的副作用。

而对于 `feb-alive`而言，`key` 是在一直前进的，所以我说他 *不稳定*。

----

所以我只是想描述 **失活缓存** 的问题。。。

另外大佬打算咋解决这个问题，我比较着急，所以先在 `render` 里面，判断了 `this._inactive` 。

**Comment by hangaoke1** [comment]
v2.02中已经解决。如果存在匹配vnode，feb-alive会向上寻找是否存在父组建_inactive，如果存在就返回null

**Comment by Dante-dan** [comment]
看到啦~我先测测

**Comment by Dante-dan** [comment]
emmmmmm, 我刚刚测了下，直接升级后，有的路由好像不展示。

`parent._inactive` 好像和路由的变化不是同步的。具体我在看看~

**Comment by hangaoke1** [comment]
https://github.com/vuejs/vue-router/blob/677f3c1f714fb61cc495345e535409b1cbb90429/src/components/view.js#L42，
router-view组件本身也有同样的判断，你反馈部分路由不展示，能来个reopen吗？

**Comment by Dante-dan** [comment]
没问题了。我没仔细看，sorry。
