### ISSUE TITLE
带参数的路由返回后页面变空白

### ISSUE THREAD

**Issue by playersun** [wefront/feb-alive#17]
路由地址是：/community/abur/parentId/409474825232387/type/4
路由配置是：{path: '/community/abur/parentId/:parentId?/type/:type?', name: 'communityAbur', component: communityAbur}

返回调用的是Vue.router.back()， 返回后页面就变成空白的了。
这个页面是公用的，就像省市区一样，点击列表一级一级往下进入。不清楚是不是这个原因。

**Comment by hangaoke1** [comment]
使用this.$location.back() 试试，如果还不行，麻烦能提供一个repo仓库复现一下吗

**Comment by playersun** [comment]
> 使用this.$location.back() 试试，如果还不行，麻烦能提供一个repo仓库复现一下吗

不好意思，可以加我微信私发给您吧？wx：sun_left

**Comment by hangaoke1** [comment]
业务逻辑测问题 closed
