### ISSUE TITLE
BUG: 不应将 debug 信息带到源码中，更不应暴露在 window 上

### ISSUE THREAD

**Issue by Dante-dan** [wefront/feb-alive#18]
https://github.com/wefront/feb-alive/blob/3fb1dcc1b4e36007ee857f0c070b4598ded7317f/src/cache.js#L9

代码中直接将 debug 信息暴露在 window 上，首先这不安全。

其次，由于 `cache_debug[depth] = this.cache` ，`cache_debug` 持有了组件内部的 `cache` 变量，当 `feb-alive` 正常的创建和销毁时，无法正常释放掉变量 `cache` ，存在内存泄漏的隐患。

**Comment by hangaoke1** [comment]
done，建议可以fork一个自己做后续优化
