### ISSUE TITLE
页面replace跳转之后缓存实例未清除

### ISSUE THREAD

**Issue by jian-qin** [wefront/feb-alive#2]
虽然功能没问题，但是多次replace跳转之后，会缓存一堆重复的页面实例，造成内存资源浪费；希望作者大佬修复一下这个问题。
[截图](https://user-images.githubusercontent.com/53079082/74132281-34b30280-4c21-11ea-86cc-073377d040af.png)

**Comment by hangaoke1** [comment]
问题已经找到，近期会发版本优化

**Comment by jian-qin** [comment]
嗯嗯，因为存在缓存数量限制，很容易就会超过默认10个数量，所以这个问题还是挺严重的。
之前用的是vue-navigation就完全没有考虑要清除缓存，因为没有数量限制就也还能用，不过看作者好像弃坑了。

**Comment by hangaoke1** [comment]
1.0.9版本已经修复
