### ISSUE TITLE
Demo中从tree-ancestor/tree-parent跳转到tree-ancestor/tree-parent/tree-son. 回退到tree-ancestor/tree-parent状态未保持

### ISSUE THREAD

**Issue by smalt762581** [wefront/feb-alive#21]
<img width="735" alt="截屏2022-07-21 22 48 16" src="https://user-images.githubusercontent.com/29419090/180244011-af59181a-7fd3-4ef3-bfaa-068ab2d09a28.png">
<img width="744" alt="截屏2022-07-21 22 49 45" src="https://user-images.githubusercontent.com/29419090/180244339-3302facb-93c1-497c-8069-fc640228d22c.png">
如图 在demo的home组件添加直接到treeParent组件的路由，并且在treeParent中添加路由到treeSon.

1. 在tree-ancestor/tree-parent修改count，去到tree-ancestor/tree-parent/tree-son 同样修改状态

2. 回退到tree-ancestor/tree-parent状态未保持

3. 前进到tree-ancestor/tree-parent/tree-son 状态也未保持

**Comment by hangaoke1** [comment]
https://github.com/wefront/feb-alive/blob/master/src/components/feb-alive.js#L115
上层组件复用情况
```js
/a/b/c => /a/b/d // 复用a、b组件

/a/b/c => /a/e // 复用a组件
```

所以以下情况不会复用组件，a、b
```s
/a/b => /a/b/c
```

临时解决方案，增加一个空的匹配组件home
```s
/a/b/home => /a/b/c
```

**Comment by smalt762581** [comment]
对于 /a/b => /a/b/c 不复用a、b是没有疑问的

疑惑的点在于回退的时候 却没有复用


父路由只有一层的时候：

a => a/b  走到else 此时不会复用a

但是a/b 回退到 a  满足if 此时a是复用的

父路由有两层的时候

a/b => a/b/c 走到else 不复用a、b

但是从a/b/c 回退到 回到a/b 满足if  但是 a、b也没有复用

**Comment by hangaoke1** [comment]
确实有这个问题，这边修复一下

**Comment by hangaoke1** [comment]
## 路由复用说明

### 嵌套路由跳多层嵌套路由：
```
/a/b => /a/b/c
```
a复用/b复用/c创建


### 多层嵌套路由跳嵌套路由：
```
/a/b/c => /a/b
```
a复用/b创建


### 多层嵌套路由同末级跳转：
```
/a/b/c => /a/b/c?t=xxxx
```

a复用/b复用/c创建


### 嵌套路由同末级跳转：
```
/a/b => /a/b?t=xxxx
```
a复用/b创建

**Comment by hangaoke1** [comment]
Fixed in 2.1.0
