### ISSUE TITLE
滚动条缓存封装（不是提bug）

### ISSUE THREAD

**Issue by jian-qin** [wefront/feb-alive#3]
只是一个优化建议，并不是提一个bug。

原因：页面缓存并没有保存滚动条位置，对用户体验不友好。

我现在的解决方案：

代码：[截图](https://user-images.githubusercontent.com/53079082/74207937-94122080-4cbc-11ea-8673-2ee318ff90f6.png)

原理：在页面跳转时存储并设置滚动条位置，将页面中class="_scroll"的滚动条数值存储在this._scroll中；当页面存在多个class="_scroll"时，只会对最后一个生效。

这个是用来配合feb-alive使用的，如果能把滚动条也封装那就更好了；
谢谢作者大佬的feb-alive。

**Comment by hangaoke1** [comment]
感谢建议，目前项目里滚动位置一般是通过配置vue-router的scrollBehavior实现的

**Comment by jian-qin** [comment]
额，好吧。这scrollBehavior只记录页面文档滚动位置，没有记录局部元素的滚动位置，有局限性对我来说没啥用。

**Comment by hangaoke1** [comment]
局部情况比较多，比如一个页面可能有多个局部滚动容器，所以这部分主要还是业务实现，不过你这个建议可以考虑插件提供一个公共方法简化业务使用类似业务需求

**Comment by hangaoke1** [comment]
局部容器滚动高度建议自行封装scroll-view组件，将滚动高度同步保存至组件的data属性上，可参考uni-app在H5下实现的scroll-view组件
