### ISSUE TITLE
这个 route 没有在上下文中出现过。请问这个变量从哪里来？

### ISSUE THREAD

**Issue by Dante-dan** [wefront/feb-alive#5]
这个地方是想写 `router` 还是 `router.route` 呢？

而且这个 route 变量也没有被使用到呀? 从这里看，传与不传没有区别呀

https://github.com/wefront/feb-alive/blob/6cab419a00ab4ce04abb6a982da6d91c06761133/src/index.js#L125

https://github.com/wefront/feb-alive/blob/6cab419a00ab4ce04abb6a982da6d91c06761133/src/index.js#L94

**Comment by hangaoke1** [comment]
哈哈，这里应该是matchRoute，因为之前维护了内外双版本，没同步好，已fix

**Comment by hangaoke1** [comment]
fixed v1.0.10
